# Generated by Django 3.2.5 on 2022-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0002_auto_20220114_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='author_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
