# Generated by Django 3.2.5 on 2022-01-21 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utilisateur', '0001_initial'),
        ('Evenement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evenement.contrat'),
        ),
        migrations.AddField(
            model_name='event',
            name='supportContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.client'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='salesContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
